import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'bs' | 'en';
export type Localized = Record<Locale, string>;

const copy: Record<Locale, Record<string, string>> = {
  bs: {
    'nav.home': 'Početna', 'nav.menu': 'Meni', 'nav.about': 'O nama', 'nav.gallery': 'Galerija', 'nav.reservations': 'Rezervacije', 'nav.contact': 'Kontakt', 'nav.order': 'Naruči',
    'nav.open': 'Otvori navigaciju', 'nav.close': 'Zatvori navigaciju', 'nav.label': 'Glavna navigacija', 'nav.mobileLabel': 'Mobilna navigacija', 'nav.brand': 'Savorelle početna',
    'hero.kicker': 'Savorelle, Sarajevo', 'hero.line1': 'Uživajte u', 'hero.line2': 'svakom trenutku', 'hero.line3': 'svakog zalogaja', 'hero.copy': 'Savremena kuhinja, pažljivo birani sastojci i atmosfera zbog koje večer ostaje u sjećanju.', 'hero.reserve': 'Rezervišite sto',
    'hero.feature1.title': 'Posebni događaji', 'hero.feature1.copy': 'Vaš važan trenutak pretvaramo u lijepu večer', 'hero.feature2.title': 'Chefovo iskustvo', 'hero.feature2.copy': 'Kuhinja otvorena prema stolu i detalju', 'hero.feature3.title': 'Jela s potpisom', 'hero.feature3.copy': 'Poznati okusi pripremljeni s karakterom',
    'home.eyebrow': 'Savremena kuhinja', 'home.title': 'Mjesto gdje se okus pamti.', 'home.copy': 'Istražite pažljivo složen meni, pripremljen s mjerom, toplinom i osjećajem za trenutak.', 'home.fullMenu': 'Pogledajte cijeli meni', 'home.storyEyebrow': 'Naša priča', 'home.storyTitle': 'Neka okus vodi put.', 'home.storyCopy': 'Savorelle je više od lijepog tanjira. Svaka posjeta je oblikovana toplinom, dobrim tajmingom, poznatom velikodušnošću i sastojcima koje biramo pažljivo.', 'home.storyLink': 'Otkrijte našu priču', 'home.atmosphere': 'Atmosfera', 'home.atmosphereTitle': 'Večer se razvija u toplom svjetlu, uz elegantne tanjire i tih razgovor.', 'home.galleryLink': 'Istražite galeriju',
    'menu.label': 'Naš meni', 'menu.title': 'Putovanje kroz okuse, slijed po slijed.', 'menu.copy': 'Meni inspirisan lokalnim navikama, sezonom i savremenom kuhinjom.', 'menu.recommendation': 'Preporuka chefa', 'menu.signatureTitle': 'Savorelle Burger', 'menu.signatureCopy': 'Sočni burger od junetine, brioche pecivo, domaći sos i hrskavi pomfrit. Jednostavno, raskošno i pripremljeno po narudžbi.', 'menu.ingredients': 'Sastojci', 'menu.ingredientsValue': 'Junetina, brioche, sir, salata, Savorelle sos', 'menu.fromChef': 'Iz kuhinje', 'menu.fromChefValue': '“Najbolje jelo je ono kojem se vraćate.”', 'menu.index': 'Kategorije menija', 'menu.dietaryTitle': 'Oznake u meniju', 'menu.dietaryCopy': 'V vegetarijansko · VG vegansko · GF bez glutena · SP ljuto. Molimo navedite alergije pri rezervaciji ili narudžbi.', 'menu.ctaEyebrow': 'Napravite večer od toga', 'menu.ctaTitle': 'Spremni za Savorelle iskustvo?', 'menu.reserve': 'Rezervišite sto', 'menu.viewReservations': 'Rezervacije',
    'about.label': 'O Savorelleu', 'about.title': 'Hrana je naš jezik. Gostoprimstvo je naša duša.', 'about.copy': 'Restoran za dijeljenje tanjira, ugodno svjetlo i male detalje zbog kojih večer traje duže.', 'about.storyEyebrow': 'Naša priča', 'about.storyTitle': 'Počelo je s vjerovanjem da večera treba usporiti svijet.', 'about.story1': 'Savorelle je zamišljen kao prostor za apetit i razgovor. Kuhanje počinje sa sezonom, prolazi kroz vatru kuhinje i dolazi do stola bez suvišne buke.', 'about.story2': 'Vjerujemo da gostoprimstvo nije predstava. To je siguran doček, savršeno tempirano piće i tim koji zna kada stolu treba dati mir.', 'about.chefEyebrow': 'Chef kuhinje', 'about.chefCopy': 'Nakon rada u evropskim kuhinjama, Elena spaja klasičnu disciplinu i direktne, živopisne okuse. Njeni tanjiri su zasnovani na sezoni, sjećanju i preciznoj ravnoteži.', 'about.quote': '“Najbolji sastojak na svakom tanjiru je osjećaj da je pripremljen baš za vas.”', 'about.sourceEyebrow': 'Sastojci i porijeklo', 'about.sourceTitle': 'Blizu sezone. Blizu izvora.', 'about.sourceCopy': 'Tražimo male proizvođače, svježe namirnice i sastojke koji već imaju priču prije nego uđu u našu kuhinju.', 'about.craftEyebrow': 'Zanat', 'about.craftTitle': 'Preciznost, vatra i posljednji tihi detalj.', 'about.craftCopy': 'Priprema počinje rano. Svaki sos, komad tijesta i završni dodir grade se tako da do vašeg stola stignu u pravom trenutku.',
    'gallery.label': 'Galerija', 'gallery.title': 'Pogled u Savorelle iskustvo.', 'gallery.copy': 'Tanjir, prostor, vatra i ritual: prizori iz restorana koji je napravljen da se doživljava polako.', 'gallery.all': 'Sve', 'gallery.cuisine': 'Hrana', 'gallery.interior': 'Enterijer', 'gallery.chef': 'Chef', 'gallery.atmosphere': 'Atmosfera', 'gallery.filters': 'Filteri galerije', 'gallery.open': 'Otvori sliku', 'gallery.close': 'Zatvori galeriju', 'gallery.previous': 'Prethodna slika', 'gallery.next': 'Sljedeća slika',
    'reservation.label': 'Rezervacije', 'reservation.title': 'Vaš sto vas čeka.', 'reservation.copy': 'Savorelle sto je mali prostor u večeri, sačuvan samo za vas. Recite nam šta imate na umu.', 'reservation.eyebrow': 'Rezervišite sto', 'reservation.heading': 'Odvojite trenutak. Mi ćemo se pobrinuti za ostalo.', 'reservation.step1': 'Odaberite sto', 'reservation.step2': 'Vaši podaci', 'reservation.step3': 'Učinite rezervaciju svojom', 'reservation.guests': 'Broj gostiju', 'reservation.date': 'Datum', 'reservation.time': 'Vrijeme', 'reservation.firstName': 'Ime', 'reservation.lastName': 'Prezime', 'reservation.email': 'Email', 'reservation.phone': 'Telefon', 'reservation.occasion': 'Povod', 'reservation.requests': 'Posebne napomene', 'reservation.selectTime': 'Odaberite vrijeme', 'reservation.noOccasion': 'Bez posebnog povoda', 'reservation.birthday': 'Rođendan', 'reservation.anniversary': 'Godišnjica', 'reservation.business': 'Poslovna večera', 'reservation.romantic': 'Romantična večera', 'reservation.other': 'Drugo', 'reservation.placeholder': 'Alergije, pristupačnost ili napomena za naš tim', 'reservation.footer': 'Vaš zahtjev se čuva u Savorelle sistemu rezervacija. Dostupnost potvrđujemo emailom.', 'reservation.submit': 'Pošaljite rezervaciju', 'reservation.loading': 'Pripremamo vaš sto...', 'reservation.successTitle': 'Vaš sto je u pripremi.', 'reservation.successCopy': 'Primili smo vaš zahtjev i uskoro ćemo ga potvrditi emailom.', 'reservation.successClose': 'Nazad na Savorelle', 'reservation.error': 'Molimo popunite označena polja.', 'reservation.errorGuests': 'Odaberite broj gostiju.', 'reservation.errorDate': 'Odaberite datum.', 'reservation.errorTime': 'Odaberite vrijeme.', 'reservation.errorFirst': 'Unesite ime.', 'reservation.errorLast': 'Unesite prezime.', 'reservation.errorEmail': 'Unesite ispravan email.', 'reservation.errorPhone': 'Unesite ispravan broj telefona.',
    'booking.eyebrow': 'Prije dolaska', 'booking.title': 'Detalji za lijepu večer.', 'booking.hours': 'Radno vrijeme', 'booking.duration': 'Trajanje večere', 'booking.durationCopy': 'Za večeru preporučujemo dva sata, a za degustacijski meni tri sata.', 'booking.groups': 'Grupe i privatne večere', 'booking.groupsCopy': 'Za sedam ili više gostiju kontaktirajte naš tim za privatne događaje.', 'booking.arrival': 'Dolazak i otkazivanje', 'booking.arrivalCopy': 'Ako se planovi promijene, javite nam 24 sata ranije. Sto čuvamo 15 minuta.', 'faq.eyebrow': 'Pitanja i odgovori', 'faq.title': 'Korisni detalji prije posjete.',
    'contact.label': 'Kontakt', 'contact.title': 'Dođite na večeru.', 'contact.copy': 'Pronađite prostor, sto i ljude koji stoje iza dobrodošlice. Tu smo da isplaniramo vašu večer.', 'contact.eyebrow': 'Osnovne informacije', 'contact.heading': 'Sve što trebate prije dolaska.', 'contact.address': 'Adresa', 'contact.reservations': 'Rezervacije', 'contact.hours': 'Radno vrijeme', 'contact.map': 'Prostor za mapu', 'contact.directions': 'Upute za dolazak', 'contact.arrivalEyebrow': 'Dolazak', 'contact.arrivalTitle': 'Stignite bez žurbe.', 'contact.parking': 'Parking', 'contact.parkingCopy': 'Dostupan je javni parking u blizini restorana.', 'contact.transport': 'Javni prijevoz', 'contact.transportCopy': 'Restoran je kratkom šetnjom povezan s glavnim gradskim linijama.', 'contact.taxi': 'Taxi i iskrcavanje', 'contact.taxiCopy': 'Zaustavljanje je moguće neposredno ispred restorana.', 'contact.accessibility': 'Pristupačnost', 'contact.accessibilityCopy': 'Dostupan je ulaz bez stepenica. Napišite nam svoje potrebe pri rezervaciji.', 'contact.privateEyebrow': 'Privatne večere i događaji', 'contact.privateTitle': 'Okupite se za stolom koji je samo vaš.', 'contact.privateCopy': 'Za privatne večere, poslovne prilike i mala slavlja, naš tim može oblikovati meni i prostor po vašoj mjeri.', 'contact.inquiry': 'Pošaljite upit', 'contact.noteEyebrow': 'Pošaljite poruku', 'contact.noteTitle': 'Voljeli bismo čuti od vas.', 'contact.name': 'Ime i prezime', 'contact.subject': 'Tema', 'contact.selectSubject': 'Odaberite temu', 'contact.general': 'Opće pitanje', 'contact.message': 'Poruka', 'contact.optional': 'opcionalno', 'contact.response': 'Odgovaramo u roku od jednog radnog dana.', 'contact.sent': 'Hvala. Vaša poruka je spremna za Savorelle tim.', 'contact.send': 'Pošaljite poruku',
    'order.label': 'Naručite', 'order.title': 'Savorelle, gdje god vaša večer počinje.', 'order.copy': 'Odaberite preuzimanje ili dostavu. Plaćanje i dostava se mogu povezati kada izaberete partnera.', 'order.pickup': 'Preuzimanje', 'order.delivery': 'Dostava', 'order.type': 'Vrsta narudžbe', 'order.categories': 'Kategorije', 'order.cartEyebrow': 'Vaša narudžba', 'order.empty': 'Odabrana jela će se pojaviti ovdje.', 'order.remove': 'Ukloni', 'order.subtotal': 'Osnovna cijena', 'order.deliveryFee': 'Dostava', 'order.total': 'Ukupno za platiti', 'order.deliveryZone': 'Zona dostave', 'order.deliveryEstimate': 'Procjena dostave je prikazana prije plaćanja.', 'order.central': 'Centar Sarajeva', 'order.outer': 'Šire gradsko područje', 'order.extended': 'Van gradske zone', 'order.freePickup': 'Preuzimanje u restoranu je bez naknade.', 'order.demo': 'Demo narudžba. Plaćanje, adresa i dostava spremni su za povezivanje s budućim backendom.', 'order.continue': 'Nastavite na podatke', 'order.add': 'Dodajte jedan', 'order.subtract': 'Uklonite jedan',
    'common.reserveEyebrow': 'Rezervišite', 'common.reserveTitle': 'Rezervišite sto za svoju sljedeću omiljenu večer.', 'common.reserveButton': 'Rezervišite sto', 'footer.tagline': 'Mjesto gdje se okus susreće s elegancijom.', 'footer.navigation': 'Navigacija u podnožju', 'footer.social': 'Instagram / Facebook / Mapa',
    'seo.homeTitle': 'Savorelle | Savremena kuhinja u Sarajevu', 'seo.homeDesc': 'Savorelle je restoran za pažljivo pripremljene okuse, atmosferu i večere koje se pamte.', 'seo.menuTitle': 'Meni | Savorelle', 'seo.menuDesc': 'Istražite Savorelle meni sa lokalno inspirisanim jelima i cijenama u KM.', 'seo.aboutTitle': 'O nama | Savorelle', 'seo.aboutDesc': 'Upoznajte priču, kuhinju i gostoprimstvo iza Savorellea.', 'seo.galleryTitle': 'Galerija | Savorelle', 'seo.galleryDesc': 'Pogledajte atmosferu, jela i detalje Savorelle restorana.', 'seo.reservationTitle': 'Rezervacije | Savorelle', 'seo.reservationDesc': 'Rezervišite sto u Savorelleu za svoju sljedeću večeru.', 'seo.contactTitle': 'Kontakt | Savorelle', 'seo.contactDesc': 'Kontaktirajte Savorelle i pronađite informacije za dolazak.', 'seo.orderTitle': 'Naručite | Savorelle', 'seo.orderDesc': 'Pregledajte Savorelle ponudu za preuzimanje i dostavu.',
  },
  en: {
    'nav.home': 'Home', 'nav.menu': 'Menu', 'nav.about': 'About', 'nav.gallery': 'Gallery', 'nav.reservations': 'Reservations', 'nav.contact': 'Contact', 'nav.order': 'Order',
    'nav.open': 'Open navigation', 'nav.close': 'Close navigation', 'nav.label': 'Main navigation', 'nav.mobileLabel': 'Mobile navigation', 'nav.brand': 'Savorelle home',
    'hero.kicker': 'Savorelle, Sarajevo', 'hero.line1': 'Savor every', 'hero.line2': 'moment of', 'hero.line3': 'every bite', 'hero.copy': 'Modern cooking, carefully chosen ingredients, and an atmosphere that makes an evening stay with you.', 'hero.reserve': 'Reserve your table',
    'hero.feature1.title': 'Special events', 'hero.feature1.copy': 'We make your important moment a beautiful evening', 'hero.feature2.title': 'Chef’s experience', 'hero.feature2.copy': 'A kitchen open to the table and every detail', 'hero.feature3.title': 'Signature dishes', 'hero.feature3.copy': 'Familiar flavors prepared with character',
    'home.eyebrow': 'Modern dining', 'home.title': 'A place where flavor lingers.', 'home.copy': 'Explore a considered menu prepared with restraint, warmth, and a sense of occasion.', 'home.fullMenu': 'View the full menu', 'home.storyEyebrow': 'Our story', 'home.storyTitle': 'Let flavor lead the way.', 'home.storyCopy': 'Savorelle is more than a beautiful plate. Each visit is shaped by warmth, good timing, familiar generosity, and ingredients we choose with care.', 'home.storyLink': 'Discover our story', 'home.atmosphere': 'Atmosphere', 'home.atmosphereTitle': 'The evening unfolds in warm light, elegant plates, and low conversation.', 'home.galleryLink': 'Explore gallery',
    'menu.label': 'Our menu', 'menu.title': 'A journey through flavor, course by course.', 'menu.copy': 'A menu inspired by local habits, the season, and modern cooking.', 'menu.recommendation': 'Chef’s recommendation', 'menu.signatureTitle': 'Savorelle Burger', 'menu.signatureCopy': 'A juicy beef burger, brioche bun, house sauce, and crisp fries. Simple, generous, and made to order.', 'menu.ingredients': 'Ingredients', 'menu.ingredientsValue': 'Beef, brioche, cheese, salad, Savorelle sauce', 'menu.fromChef': 'From the kitchen', 'menu.fromChefValue': '“The best dish is the one you return to.”', 'menu.index': 'Menu categories', 'menu.dietaryTitle': 'Menu notes', 'menu.dietaryCopy': 'V vegetarian · VG vegan · GF gluten-free · SP spicy. Please share allergies when reserving or ordering.', 'menu.ctaEyebrow': 'Make an evening of it', 'menu.ctaTitle': 'Ready for the Savorelle experience?', 'menu.reserve': 'Reserve a table', 'menu.viewReservations': 'Reservations',
    'about.label': 'About Savorelle', 'about.title': 'Food is our language. Hospitality is our soul.', 'about.copy': 'A restaurant for shared plates, warm light, and the small details that make an evening linger.', 'about.storyEyebrow': 'Our story', 'about.storyTitle': 'It began with a belief: dinner should slow the world down.', 'about.story1': 'Savorelle was imagined as a room for appetite and conversation. Our cooking starts with the season, travels through the heat of the kitchen, and reaches the table without unnecessary noise.', 'about.story2': 'We believe hospitality is not a performance. It is a confident welcome, a perfectly timed drink, and a team that knows when to let a table have its own moment.', 'about.chefEyebrow': 'Chef of the kitchen', 'about.chefCopy': 'After working in European kitchens, Elena brings together classical discipline and direct, vivid flavors. Her plates are grounded in season, memory, and exact balance.', 'about.quote': '“The best ingredient on every plate is the feeling that it was made just for you.”', 'about.sourceEyebrow': 'Ingredients and sourcing', 'about.sourceTitle': 'Close to the season. Close to the source.', 'about.sourceCopy': 'We seek out small growers, fresh produce, and ingredients that already have a story before entering our kitchen.', 'about.craftEyebrow': 'Craft', 'about.craftTitle': 'Precision, fire, and the final quiet detail.', 'about.craftCopy': 'Preparation begins early. Every sauce, dough, and final touch is built to reach your table at precisely the right moment.',
    'gallery.label': 'Gallery', 'gallery.title': 'A glimpse into the Savorelle experience.', 'gallery.copy': 'Plate, room, flame, and ritual: scenes from a restaurant designed to be experienced slowly.', 'gallery.all': 'All', 'gallery.cuisine': 'Food', 'gallery.interior': 'Interior', 'gallery.chef': 'Chef', 'gallery.atmosphere': 'Atmosphere', 'gallery.filters': 'Gallery filters', 'gallery.open': 'Open image', 'gallery.close': 'Close gallery', 'gallery.previous': 'Previous image', 'gallery.next': 'Next image',
    'reservation.label': 'Reservations', 'reservation.title': 'Your table awaits.', 'reservation.copy': 'A Savorelle table is a little space held in the evening just for you. Tell us what you have in mind.', 'reservation.eyebrow': 'Reserve your table', 'reservation.heading': 'Take your time. We will take care of the rest.', 'reservation.step1': 'Choose your table', 'reservation.step2': 'Your details', 'reservation.step3': 'Make it yours', 'reservation.guests': 'Guests', 'reservation.date': 'Date', 'reservation.time': 'Time', 'reservation.firstName': 'First name', 'reservation.lastName': 'Last name', 'reservation.email': 'Email', 'reservation.phone': 'Phone', 'reservation.occasion': 'Occasion', 'reservation.requests': 'Special requests', 'reservation.selectTime': 'Select a time', 'reservation.noOccasion': 'No special occasion', 'reservation.birthday': 'Birthday', 'reservation.anniversary': 'Anniversary', 'reservation.business': 'Business dinner', 'reservation.romantic': 'Romantic dinner', 'reservation.other': 'Other', 'reservation.placeholder': 'Allergies, accessibility, or a note for our team', 'reservation.footer': 'Your request is saved in Savorelle’s reservation system. We confirm availability by email.', 'reservation.submit': 'Request reservation', 'reservation.loading': 'Preparing your table...', 'reservation.successTitle': 'Your table is in motion.', 'reservation.successCopy': 'We received your request and will confirm it by email shortly.', 'reservation.successClose': 'Return to Savorelle', 'reservation.error': 'Please complete the highlighted fields.', 'reservation.errorGuests': 'Choose guest count.', 'reservation.errorDate': 'Choose a date.', 'reservation.errorTime': 'Choose a time.', 'reservation.errorFirst': 'Enter your first name.', 'reservation.errorLast': 'Enter your last name.', 'reservation.errorEmail': 'Enter a valid email.', 'reservation.errorPhone': 'Enter a valid phone number.',
    'booking.eyebrow': 'Before you arrive', 'booking.title': 'Details for a beautiful evening.', 'booking.hours': 'Opening hours', 'booking.duration': 'Dining duration', 'booking.durationCopy': 'We recommend allowing two hours for dinner and three hours for tasting menus.', 'booking.groups': 'Groups and private dining', 'booking.groupsCopy': 'For seven or more guests, contact our private events team.', 'booking.arrival': 'Arrival and cancellations', 'booking.arrivalCopy': 'If plans change, please tell us 24 hours ahead. We hold tables for 15 minutes.', 'faq.eyebrow': 'Questions, answered', 'faq.title': 'Helpful details before your visit.',
    'contact.label': 'Contact', 'contact.title': 'Come dine with us.', 'contact.copy': 'Find the room, the table, and the people behind the welcome. We are here to help you plan your evening.', 'contact.eyebrow': 'Essential information', 'contact.heading': 'Everything you need before you arrive.', 'contact.address': 'Address', 'contact.reservations': 'Reservations', 'contact.hours': 'Opening hours', 'contact.map': 'Map area', 'contact.directions': 'Get directions', 'contact.arrivalEyebrow': 'Getting here', 'contact.arrivalTitle': 'Arrive with ease.', 'contact.parking': 'Parking', 'contact.parkingCopy': 'Public parking is available close to the restaurant.', 'contact.transport': 'Public transport', 'contact.transportCopy': 'The restaurant is a short walk from the main city routes.', 'contact.taxi': 'Taxi and drop-off', 'contact.taxiCopy': 'Drop-off is available directly in front of the restaurant.', 'contact.accessibility': 'Accessibility', 'contact.accessibilityCopy': 'A step-free entrance is available. Tell us about your needs in your reservation.', 'contact.privateEyebrow': 'Private dining and events', 'contact.privateTitle': 'Gather around a table that is yours alone.', 'contact.privateCopy': 'For private dinners, business occasions, and small celebrations, our team can shape a menu and room around you.', 'contact.inquiry': 'Start an inquiry', 'contact.noteEyebrow': 'Send a note', 'contact.noteTitle': 'We would love to hear from you.', 'contact.name': 'Full name', 'contact.subject': 'Subject', 'contact.selectSubject': 'Select a subject', 'contact.general': 'General question', 'contact.message': 'Message', 'contact.optional': 'optional', 'contact.response': 'We reply within one business day.', 'contact.sent': 'Thank you. Your note is ready for the Savorelle team.', 'contact.send': 'Send message',
    'order.label': 'Order now', 'order.title': 'Savorelle, wherever your evening begins.', 'order.copy': 'Choose pickup or delivery. Payments and delivery can be connected when you choose a partner.', 'order.pickup': 'Pickup', 'order.delivery': 'Delivery', 'order.type': 'Order type', 'order.categories': 'Categories', 'order.cartEyebrow': 'Your order', 'order.empty': 'Your selected dishes will appear here.', 'order.remove': 'Remove', 'order.subtotal': 'Items subtotal', 'order.deliveryFee': 'Delivery fee', 'order.total': 'Total to pay', 'order.deliveryZone': 'Delivery zone', 'order.deliveryEstimate': 'Your delivery estimate is shown before payment.', 'order.central': 'Central Sarajevo', 'order.outer': 'Wider city area', 'order.extended': 'Outside city area', 'order.freePickup': 'Restaurant pickup has no added fee.', 'order.demo': 'Demo ordering flow. Payments, address validation, and delivery are ready for future backend integration.', 'order.continue': 'Continue to details', 'order.add': 'Add one', 'order.subtract': 'Remove one',
    'common.reserveEyebrow': 'Reserve', 'common.reserveTitle': 'Book a table for your next favorite evening.', 'common.reserveButton': 'Reserve your table', 'footer.tagline': 'Where taste meets elegance.', 'footer.navigation': 'Footer navigation', 'footer.social': 'Instagram / Facebook / Map',
    'seo.homeTitle': 'Savorelle | Modern dining in Sarajevo', 'seo.homeDesc': 'Savorelle is a restaurant for considered flavors, atmosphere, and evenings worth remembering.', 'seo.menuTitle': 'Menu | Savorelle', 'seo.menuDesc': 'Explore the Savorelle menu with locally inspired dishes and BAM prices.', 'seo.aboutTitle': 'About | Savorelle', 'seo.aboutDesc': 'Meet the story, kitchen, and hospitality behind Savorelle.', 'seo.galleryTitle': 'Gallery | Savorelle', 'seo.galleryDesc': 'See the atmosphere, dishes, and details of Savorelle restaurant.', 'seo.reservationTitle': 'Reservations | Savorelle', 'seo.reservationDesc': 'Reserve a table at Savorelle for your next evening.', 'seo.contactTitle': 'Contact | Savorelle', 'seo.contactDesc': 'Contact Savorelle and find details for your visit.', 'seo.orderTitle': 'Order | Savorelle', 'seo.orderDesc': 'Browse Savorelle pickup and delivery options.',
  },
};

type LanguageContextValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => localStorage.getItem('savorelle-language') === 'en' ? 'en' : 'bs');
  useEffect(() => { localStorage.setItem('savorelle-language', locale); document.documentElement.lang = locale; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: string) => copy[locale][key] ?? key }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}

export function localize(value: Localized, locale: Locale) { return value[locale]; }
